package com.mycompany.picnicdestination;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class AddDestination extends javax.swing.JFrame {

    private ResultSet ResultSetDb = null;
    private PreparedStatement PreparedStatementDb = null;
    private Connection ConnectionDb = null;
    private final String INSERT_LOCATION_SQL = "INSERT INTO DestinationTbl"
            + "  (picnic_name, venue, price) VALUES "
            + " (?,?,?);";
    private final String DISPLAY_DESTINATION_SQL = "SELECT * FROM ValidlocationTbl ORDER BY venue ASC";

    /**
     * Creates new form AddDestination
     */
    public AddDestination() {
        initComponents();
        listData();
    }

    private void listData() {
        try {
            ConnectionDb = SingleConnection.getConnection();
            PreparedStatementDb = ConnectionDb.prepareStatement(DISPLAY_DESTINATION_SQL);
            ResultSetDb = PreparedStatementDb.executeQuery();
            while (ResultSetDb.next()) {
                String venue = ResultSetDb.getString("venue");
                jComboLocation.addItem(venue);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // finally block used to close resources
            SingleConnection.closeStatement(PreparedStatementDb);
            SingleConnection.closeResultSet(ResultSetDb);
        }// end try
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jComboLocation = new javax.swing.JComboBox<>();
        jTxtPicnicName = new javax.swing.JTextField();
        jBtnLocation = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnLog = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jTxtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jBtnLocation1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Picnic Destination");

        jComboLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        jComboLocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboLocationItemStateChanged(evt);
            }
        });
        jComboLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLocationActionPerformed(evt);
            }
        });

        jTxtPicnicName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPicnicNameActionPerformed(evt);
            }
        });

        jBtnLocation.setText("View Tickets");
        jBtnLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLocationActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Picnic Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Venue");

        jBtnLog.setText("Logout");
        jBtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogActionPerformed(evt);
            }
        });

        jBtnAdd.setText("Add");
        jBtnAdd.setEnabled(false);
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jTxtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPriceActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Price");

        jBtnLocation1.setText("New Venue");
        jBtnLocation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLocation1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnLocation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnLog))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnLocation1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtPicnicName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTxtPicnicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAdd)
                    .addComponent(jBtnLocation1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLocation)
                    .addComponent(jBtnLog))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboLocationActionPerformed

    }//GEN-LAST:event_jComboLocationActionPerformed

    private void jBtnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLocationActionPerformed
        openAllTicket();
    }//GEN-LAST:event_jBtnLocationActionPerformed

    private void jTxtPicnicNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPicnicNameActionPerformed

    }//GEN-LAST:event_jTxtPicnicNameActionPerformed

    private void jBtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogActionPerformed
        openRegistration();
    }//GEN-LAST:event_jBtnLogActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        String venue = jComboLocation.getSelectedItem().toString();
        String picnicName = jTxtPicnicName.getText();
        try {
            double price = Double.parseDouble(jTxtPrice.getText().trim());
            try {
                ConnectionDb = SingleConnection.getConnection();
                PreparedStatementDb = ConnectionDb.prepareStatement(INSERT_LOCATION_SQL);
                PreparedStatementDb.setString(1, picnicName);
                PreparedStatementDb.setString(2, venue);
                PreparedStatementDb.setDouble(3, price);
                PreparedStatementDb.executeUpdate();
                ConnectionDb.commit();
                JOptionPane.showMessageDialog(jBtnAdd, "Data Saved");
                jTxtPicnicName.setText("");
                jTxtPrice.setText("");
                jBtnAdd.setEnabled(false);
                jComboLocation.setSelectedIndex(0);
            } catch (SQLException e) {
                if (ConnectionDb != null) {
                    try {
                        ConnectionDb.rollback();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }
                e.printStackTrace();
            } finally {
                // finally block used to close resources
                SingleConnection.closeStatement(PreparedStatementDb);
            }// end try
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(jBtnAdd, "Enter a valid price");
        }

    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jTxtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPriceActionPerformed

    }//GEN-LAST:event_jTxtPriceActionPerformed

    private void jComboLocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboLocationItemStateChanged
        if (jComboLocation.getSelectedIndex() > 0) {
            jBtnAdd.setEnabled(true);
        } else {
            jBtnAdd.setEnabled(false);
        }
    }//GEN-LAST:event_jComboLocationItemStateChanged

    private void jBtnLocation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLocation1ActionPerformed
        openNewLocation();
    }//GEN-LAST:event_jBtnLocation1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDestination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDestination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDestination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDestination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDestination().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnLocation;
    private javax.swing.JButton jBtnLocation1;
    private javax.swing.JButton jBtnLog;
    private javax.swing.JComboBox<String> jComboLocation;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTxtPicnicName;
    private javax.swing.JTextField jTxtPrice;
    // End of variables declaration//GEN-END:variables

    private void openNewLocation() {
        setVisible(false);
        new NewLocation().setVisible(true);
    }

    private void openRegistration() {
        setVisible(false);
        new Registration().setVisible(true);
    }

    private void openAllTicket() {
        setVisible(false);
        new AllTicket().setVisible(true);
    }
}
