package com.mycompany.picnicdestination;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

public class NewLocation extends javax.swing.JFrame {

    private ResultSet ResultSetDb = null;
    private PreparedStatement PreparedStatementDb = null;
    private Connection ConnectionDb = null;
    private final String INSERT_LOCATION_SQL = "INSERT INTO ValidlocationTbl"
            + "  (venue) VALUES "
            + " (?);";
    private final String DELETE_LOCATION_SQL = "DELETE FROM LocationTbl WHERE venue=?";
    private final String DISPLAY_LOCATION_SQL = "SELECT * FROM LocationTbl ORDER BY venue ASC";
    private DefaultListModel ListModel = new DefaultListModel();

    /**
     * Creates new form NewLocation
     */
    public NewLocation() {
        initComponents();
        listData();
    }

    private List<String> getAllLocation() {
        List<String> locations = new ArrayList<>();
        try {
            ConnectionDb = SingleConnection.getConnection();
            PreparedStatementDb = ConnectionDb.prepareStatement(DISPLAY_LOCATION_SQL);
            ResultSetDb = PreparedStatementDb.executeQuery();
            while (ResultSetDb.next()) {
                String venue = ResultSetDb.getString("venue");
                locations.add(venue);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // finally block used to close resources
            SingleConnection.closeStatement(PreparedStatementDb);
            SingleConnection.closeResultSet(ResultSetDb);
        }// end try
        return locations;
    }

    private void listData() {
        List<String> locations = getAllLocation();
        for (String location : locations) {
            ListModel.addElement(location);
        }
        jListLocation.setModel(ListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBtnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListLocation = new javax.swing.JList<>();
        jBtnAddLocation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("New Venue");

        jBtnBack.setText("Back");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jListLocation.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListLocation.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListLocationValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListLocation);

        jBtnAddLocation.setText("Add");
        jBtnAddLocation.setEnabled(false);
        jBtnAddLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBtnAddLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnBack))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAddLocation)
                    .addComponent(jBtnBack))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        openAddDestination();
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnAddLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddLocationActionPerformed
        String selectedValue = jListLocation.getSelectedValue();
        try {
            ConnectionDb = SingleConnection.getConnection();
            PreparedStatementDb = ConnectionDb.prepareStatement(INSERT_LOCATION_SQL);
            PreparedStatementDb.setString(1, selectedValue);
            PreparedStatementDb.executeUpdate();
            PreparedStatementDb = ConnectionDb.prepareStatement(DELETE_LOCATION_SQL);
            PreparedStatementDb.setString(1, selectedValue);
            PreparedStatementDb.executeUpdate();
            //Commit all transaction
            ConnectionDb.commit();
            int index = jListLocation.getSelectedIndex();
            if (index != -1) {
                ListModel.remove(index);
            }
            jBtnAddLocation.setEnabled(false);
        } catch (SQLException e) {
            if (ConnectionDb != null) {
                try {
                    ConnectionDb.rollback();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            e.printStackTrace();
        } finally {
            // finally block used to close resources
            SingleConnection.closeStatement(PreparedStatementDb);
        }// end try
    }//GEN-LAST:event_jBtnAddLocationActionPerformed

    private void jListLocationValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListLocationValueChanged
        jBtnAddLocation.setEnabled(true);
    }//GEN-LAST:event_jListLocationValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewLocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddLocation;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListLocation;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void openAddDestination() {
        setVisible(false);
        new AddDestination().setVisible(true);
    }
}
