package com.mycompany.picnicdestination;

import com.mycompany.picnicdestination.models.Ticket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class PreviousTicketForm extends javax.swing.JFrame {

    private Connection ConnectionDb = null;
    private PreparedStatement PreparedStatementDb = null;
    private ResultSet ResultSetDb = null;
    private final String DISPLAY_ALL_TICKET_SQL = "SELECT username, picnic_name, venue, price, date_of_order FROM TicketTbl WHERE username = ?";
    private String Username;
    private DefaultTableModel TicketModel = new DefaultTableModel();
    private final String DISPLAY_TODAY_SQL = "SELECT username, picnic_name, venue, price, date_of_order FROM TicketTbl WHERE date_of_order = (current_date) AND username = ?";
    private final String DISPLAY_YESTERDAY_SQL = "SELECT username, picnic_name, venue, price, date_of_order FROM TicketTbl WHERE date_of_order <= now() - INTERVAL '1 DAY' AND username = ?";
    private final String DISPLAY_LASTWEEK_SQL = "SELECT username, picnic_name, venue, price, date_of_order FROM TicketTbl WHERE date_of_order <= now() - INTERVAL '7 DAY' AND username = ?";

    /**
     * Creates new form PreviousTicketForm
     */
    public PreviousTicketForm() {
        initComponents();
        System.out.println(Username + " from constructor ptf");
    }

    public PreviousTicketForm(String username) {
        initComponents();
        this.Username = username;
        jLabelUser.setText("Previous Tickets for " + username);
        constructTable();
        listData(DISPLAY_ALL_TICKET_SQL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ticketTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBoxTime = new javax.swing.JComboBox<>();
        jLabelUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ticketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ticketTable);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Today", "Yesterday", "Last Week" }));
        jComboBoxTime.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTimeItemStateChanged(evt);
            }
        });

        jLabelUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        openChooseDestination();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxTimeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTimeItemStateChanged
        String value = jComboBoxTime.getSelectedItem().toString();
        switch (value) {
            case "All":
                allList();
                break;
            case "Today":
                todayList();
                break;
            case "Yesterday":
                yesterdayList();
                break;
            case "Last Week":
                lastWeekList();
                break;
        }
    }//GEN-LAST:event_jComboBoxTimeItemStateChanged

    private void todayList() {
        if (TicketModel.getRowCount() > 0) {
            for (int i = TicketModel.getRowCount() - 1; i > -1; i--) {
                TicketModel.removeRow(i);
            }
        }
        listData(DISPLAY_TODAY_SQL);
    }

    private void yesterdayList() {
        if (TicketModel.getRowCount() > 0) {
            for (int i = TicketModel.getRowCount() - 1; i > -1; i--) {
                TicketModel.removeRow(i);
            }
        }
        listData(DISPLAY_YESTERDAY_SQL);
    }

    private void lastWeekList() {
        if (TicketModel.getRowCount() > 0) {
            for (int i = TicketModel.getRowCount() - 1; i > -1; i--) {
                TicketModel.removeRow(i);
            }
        }
        listData(DISPLAY_LASTWEEK_SQL);
    }

    private void allList() {
        if (TicketModel.getRowCount() > 0) {
            for (int i = TicketModel.getRowCount() - 1; i > -1; i--) {
                TicketModel.removeRow(i);
            }
        }
        listData(DISPLAY_ALL_TICKET_SQL);
    }

    public List<Ticket> getAllTickets(String query) {
        List<Ticket> tickets = new ArrayList<>();
        try {
            ConnectionDb = SingleConnection.getConnection();
            PreparedStatementDb = ConnectionDb.prepareStatement(query);
            PreparedStatementDb.setString(1, Username);
            ResultSetDb = PreparedStatementDb.executeQuery();
            while (ResultSetDb.next()) {
                String usernameT = ResultSetDb.getString("username");
                String picnic = ResultSetDb.getString("picnic_name");
                String location = ResultSetDb.getString("venue");
                double price = ResultSetDb.getDouble("price");
                Date dateOfOrder = ResultSetDb.getTimestamp("date_of_order");
                Ticket ticket = new Ticket(usernameT, picnic, location, price, dateOfOrder);
                tickets.add(ticket);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // finally block used to close resources
            SingleConnection.closeStatement(PreparedStatementDb);
            SingleConnection.closeResultSet(ResultSetDb);
        }// end try
        return tickets;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreviousTicketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreviousTicketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreviousTicketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviousTicketForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreviousTicketForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxTime;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ticketTable;
    // End of variables declaration//GEN-END:variables

    private void listData(String query) {
        List<Ticket> tickets = getAllTickets(query);
        for (Ticket ticket : tickets) {
            TicketModel.addRow(new Object[]{ticket.getUsernameT(), ticket.getPicnicName(), ticket.getLocation(), ticket.getPrice(), ticket.getDate()});
        }
    }

    private void openChooseDestination() {
        setVisible(false);
        new ChooseDestination(Username).setVisible(true);
    }

    private void constructTable() {
        TicketModel.addColumn("Username");
        TicketModel.addColumn("Picnic Name");
        TicketModel.addColumn("Venue");
        TicketModel.addColumn("Price");
        TicketModel.addColumn("Date of Order");
        ticketTable.setModel(TicketModel);
    }
}
